version: '2'

catalog:
  name: CPA/MDH EJ Instance
  description: |
    CPA EJ Environment
  version: 0.1-rancher0
  minimum_rancher_version: v1.0.0
  maintainer: "Fábio Macêdo Mendes <fabiommendes@gmail.com>"
  uuid: ejplatform
  questions:
    - variable: hostname
      label: Hostname
      description: "Hostname of the website (e.g.: ejplatform.org)"
      default: ejplatform.org
      required: true
      type: string
    - variable: database_password
      label: Database password
      description: What is the database password?
      default: ejplatform
      required: true
      type: password
    - variable: country
      label: Country
      description: Controls localization settings
      default: Brasil
      required: true
      type: string
    - variable: debug
      label: Enable debug settings?
      description: "WARNING: only enable debug mode in staging environments."
      default: false
      required: true
      type: boolean
    - variable: rancher_host
      description: "Sets the Rancher Host Affinity"
      label: "Rancher Host"
      required: true
      type: string
    - variable: volume_driver
      description: "Choose the Volume Driver being used.(Option: local or rancher-nfs)"
      label: "Volume Driver"
      required: true
      default: local
      type: "enum"
      options:
        - local
        - rancher-nfs

services:
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: nginx
        source_port: 80
        target_port: 80
  nginx:
    scale: 1
    start_on_create: true

  web:
    retain_ip: true
    scale: 1
    start_on_create: true

  rescue:
    scale: 1
    start_on_create: true

  redis:
    scale: 1
    start_on_create: true

  postgres:
    scale: 1
    start_on_create: true

  mongo:
    scale: 1
    start_on_create: true

  rocketchat:
    scale: 1
    start_on_create: true
