version: '2'

volumes:
  database:
  media:
  conf:

services:
  lb:
    image: rancher/lb-service-haproxy:v0.7.6
    expose:
      - 80:80/tcp
    labels:
      rap.le_email: help@ejplatform.org
      rap.le_test: 'false'
      rap.le_host: cpa.ejplatform.org
      rap.host: cpa.ejplatform.org
      rap.client_max_body_size: 200m
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environmentAdmin

  nginx:
    image: mdhcpa/nginx:latest
    volumes:
      - media:/usr/share/nginx/html/
    links:
      - web:web
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity: ${affinity_host}

  web: &web
    image: mdhcpa/web:latest
    environment:
      DJANGO_DB_URL: psql://ej:${database_password}@postgres:5432/ej
      DJANGO_ALLOWED_HOSTS: cpa.ejplatform.org
      DJANGO_DEBUG: 'true'
    volumes:
      - media:/app/local/:nocopy
    links:
      - postgres:postgres
      - redis:redis
    command: db -m collect gunicorn
    labels:
      io.rancher.scheduler.affinity: ${affinity_host}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always

  rescue:
    << : *web
    restart: no
    command: bash

  redis:
    image: redis:3

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ej
      POSTGRES_USER: ej
      POSTGRES_PASSWORD: ${database_password}
    volumes:
      - database:/var/lib/postgresql/data
