name: EJ Platform
description: |
  EJ Production environment. This is the standard version of the EJ platform.
version: 0.1-rancher1
category: Applications
projectURl: "https://github.com/ejplatform/ej-server/"
license: AGPL v3