version: '2'

volumes:
  database:
  media:
  conf:

services:
  lb:
    image: rancher/lb-service-haproxy:v0.7.6
    expose:
    - 80:80/tcp
    labels:
      rap.le_email: help@${hostname}
      rap.le_test: 'false'
      rap.le_host: ${hostname}
      rap.host: ${hostname}
      rap.client_max_body_size: 200m
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environmentAdmin

  nginx:
    image: ejplatform/nginx:latest
    volumes:
      - media:/usr/share/nginx/html/
    links:
      - web:web
    labels:
      io.rancher.container.pull_image: always

  web: &web
    image: ejplatform/web:latest
    environment:
      DJANGO_DB_URL: psql://ej:"${database_password}"@postgres:5432/ej
      DJANGO_ALLOWED_HOSTS: ${hostname}
      DJANGO_DEBUG: 'true'
      HOSTNAME: ${hostname}
      COUNTRY: ${country}
      DEBUG: ${debug}
    volumes:
      - media:/app/local/:nocopy
    links:
      - postgres:postgres
      - redis:redis
    command: db -m collect gunicorn
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always

  rescue:
    << : *web
    command: bash

  redis:
    image: redis:3

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ej
      POSTGRES_USER: ej
      POSTGRES_PASSWORD: ${database_password}
    volumes:
      - database:/var/lib/postgresql/data
