version: '2'

catalog:
  name: EJ Platform
  description: |
    EJ Platform Environment
  version: 0.1-rancher0
  minimum_rancher_version: v1.0.0
  maintainer: "Fábio Macêdo Mendes <fabiommendes@gmail.com>"
  uuid: ejplatform-0
  questions:
    - variable: database_password
      label: What is the database password?
      default: ejplatform
      required: true
      type: password
    - variable: hostname
      label: Hostname of the website (e.g.: ejplatform.org)
      default: ejplatform.org
      required: true
      type: string
    - variable: country
      label: Locale for the installation
      default: Brasil
      required: true
      type: string
    - variable: debug
      label: Enable DEBUG=true settings in Django?
      description: WARNING: only enable debug mode in staging environments.
      default: false
      required: true
      type: boolean

services:
  loadbalancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: nginx
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000

  nginx:
    scale: 1
    start_on_create: true

  web:
    retain_ip: true
    scale: 1
    start_on_create: true

  bash:
    scale: 1
    start_on_create: true

  redis:
    scale: 1
    start_on_create: true

  postgres:
    scale: 1
    start_on_create: true
