version: '2'

catalog:
  name: EJ Platform
  description: |
    EJ Platform Environment
  version: 1.0-rancher1
  minimum_rancher_version: v1.0.0
  maintainer: "Raul Sanchez <rawmind@gmail.com>"
  uuid: ejprod

services:
  loadbalancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: nginx
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000

  nginx:
    scale: 1
    start_on_create: true

  web:
    retain_ip: true
    scale: 1
    start_on_create: true

  bash:
    scale: 1
    start_on_create: true

  redis:
    scale: 1
    start_on_create: true

  postgres:
    scale: 1
    start_on_create: true
